--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/SVega9848/PlayerBounty
build-by-default: true
branches:
- main
projects:
  PlayerBounty:
    path: ""
    icon: "logo.png"
    libs:
      - src: Vecnavium/FormsUI/libFormsUI
        version: ^1.1.2
...
